### PR TITLE
Add rootfs overlay which works for SLE15

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by manuelbuil** [comment]
When building Istio packages and images, we had various config files and we were wondering where should we place them. We decided to add them in the rpms because we could not find any directory in caasp-container-images including config files. You are doing the opposite, which might be fine but I can't judge, we need somebody from Z squad

**Comment by manuelbuil** [comment]
Unfortunately, I don't have experience using rootfs-overlay, so I may be asking stupid questions. This change will affect both x86 and aarch64, right? Is there anything we should be careful with from support point of view? For example, could it be that performance gets worse or something similar? thanks

**Comment by jordimassaguerpla** [comment]
> When building Istio packages and images, we had various config files and we were wondering where should we place them. We decided to add them in the rpms because we could not find any directory in caasp-container-images including config files. You are doing the opposite, which might be fine but I can't judge, we need somebody from Z squad

What @dirkmueller is doing is it is the expected way of adding additional files: https://github.com/SUSE/caasp-container-images/blob/master/ci/packaging/suse/obsfiles_maker.sh#L24

**Comment by dirkmueller** [comment]
> Unfortunately, I don't have experience using rootfs-overlay, so I may be asking stupid questions. This change will affect both x86 and aarch64, right?

I didn't add anything aarch64 specific? so no, it won't affect x86_64. performance will actually get better because we turn of functionality that we no longer support (geoip1).

**Pull request merged**
